---
kind: pipeline
type: docker
name: validate

steps:
- name: prepare
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go install goimports
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
  - go install -v github.com/go-critic/go-critic/cmd/gocritic@latest

- name: format
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go fmt
  - go vet
  - golangci-lint
  - gocritic

---
kind: pipeline
type: docker
name: build

steps:
- name: prepare
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go install github.com/prometheus/promu@latest

- name: build
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - make build

depends_on:
- lint

---
kind: pipeline
name: after
type: docker

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  when:
    status:
      - failure
      - success
depends_on:
- push
