---
kind: pipeline
type: docker
name: validate

steps:
  - name: prepare
    image: golang:1.19
    volumes:
      - name: cache
        path: /go
    commands:
      - export PATH=$${PATH}:/go/bin:/usr/local/go/bin
      - go install golang.org/x/tools/cmd/goimports@latest
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - go install github.com/go-critic/go-critic/cmd/gocritic@latest
      - goimports
      - go mod tidy
      - go mod vendor

  - name: format
    image: golang:1.19
    volumes:
      - name: cache
        path: /go
    commands:
      - export PATH=$${PATH}:/go/bin:/usr/local/go/bin
      - go fmt
      - go vet
      - golangci-lint run
      - gocritic check

volumes:
  - name: cache
    host:
      path: /data/docker/cache/prom-exp-cache

---
kind: pipeline
type: docker
name: build

steps:
  - name: prepare
    image: golang:1.19
    volumes:
      - name: cache
        path: /go
    commands:
      - go install github.com/prometheus/promu@latest

  - name: build
    image: golang:1.19
    volumes:
      - name: cache
        path: /go
    commands:
      - export PATH=$${PATH}:/go/bin:/usr/local/go/bin
      - make build

depends_on:
  - validate

volumes:
  - name: cache
    host:
      path: /data/docker/cache/prom-exp-cache

---
kind: pipeline
name: notify
type: docker

trigger:
  status:
    - success
    - failure

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status:
        - failure
        - success

depends_on:
  - validate
  - build
---
kind: signature
hmac: 87ee9f32917d05f313b2e17511fd5a440e816ef56143641f5e606c33edbe1e93

...
