---
kind: pipeline
type: docker
name: validate

steps:
  - name: prepare
    image: golang:1.19
    volumes:
      - name: deps
        path: /go
    commands:
      - export PATH=$${PATH}:/go/bin:/usr/local/go/bin
      - go install golang.org/x/tools/cmd/goimports@latest
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - go install github.com/go-critic/go-critic/cmd/gocritic@latest
      - goimports
      - go mod tidy
      - go mod vendor

  - name: format
    image: golang:1.19
    volumes:
      - name: deps
        path: /go
    commands:
      - export PATH=$${PATH}:/go/bin:/usr/local/go/bin
      - go fmt
      - go vet
      - golangci-lint
      - gocritic


---
kind: pipeline
type: docker
name: build

steps:
  - name: prepare
    image: golang:1.19
    volumes:
      - name: deps
        path: /go
    commands:
      - go install github.com/prometheus/promu@latest

  - name: build
    image: golang:1.19
    volumes:
      - name: deps
        path: /go
    commands:
      - export PATH=$${PATH}:/go/bin:/usr/local/go/bin
      - make build

depends_on:
  - validate

---
kind: pipeline
name: notify
type: docker

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status:
        - failure
        - success
depends_on:
  - build
