---
kind: pipeline
type: docker
name: validate

steps:
  - name: prepare
    image: golang:1.19
    volumes:
      - name: deps
        path: /go
    commands:
      - go install golang.org/x/tools/cmd/goimports@latest
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - go install github.com/go-critic/go-critic/cmd/gocritic@latest

  - name: format
    image: golang:1.19
    volumes:
      - name: deps
        path: /go
    commands:
      - go fmt
      - go vet
      - golangci-lint
      - gocritic

---
kind: pipeline
type: docker
name: build

steps:
  - name: prepare
    image: golang:1.19
    volumes:
      - name: deps
        path: /go
    commands:
      - go install github.com/prometheus/promu@latest

  - name: build
    image: golang:1.19
    volumes:
      - name: deps
        path: /go
    commands:
      - make build

depends_on:
  - validate

---
kind: pipeline
name: notify
type: docker

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status:
        - failure
        - success
depends_on:
  - build

---
kind: signature
hmac: d9fecad40592f7dda24e3fd15d45f6af9b4650ec33b9cc4f23c255d0f9906a04

...
