verbose: true
go:
  version: 1.19.5
  cgo: false
repository:
  path: github.com/Whyrl35/prometheus-saltstack-exporter
build:
  prefix: .
  binaries:
    - name: prometheus-saltstack-exporter
      path: .
  flags: -a -tags 'netgo static_build'
  ldflags: |
    -s
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  prefix: .
  files:
    - LICENSE
    - README.md
    - prometheus-saltstack-exporter
crossbuild:
  platforms:
    - linux/amd64
    - linux/386
    - linux/arm
    - linux/arm64
    - darwin/amd64
    - darwin/386
    - windows/amd64
    - windows/386
