style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Whyrl35/prometheus-saltstack-exporter
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - ci
        - docs
        - revert
        - style
        - test
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      ci: Continuous Integration
      docs: Documentations
      revert: Reverting commit
      style: Code Styling
      test: Tests
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
